#!/usr/bin/env python3
import os
import sys
from PySide6.QtCore import QFile
from PySide6.QtWidgets import QApplication, QLabel
from PySide6.QtUiTools import QUiLoader

from main import MainWindow

app = QApplication(sys.argv)

main = MainWindow()
main.show()

app.exec()
