#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import app
from main import MainWindow
from model import Config

the_app = app.get()

cfg = Config.load()

main = MainWindow(cfg)
main.show()

the_app.exec()
